---
# Concourse task
platform: linux

image_resource:
  type: docker-image
  source:
    repository: gradle
    tag: 'jdk8'

inputs:
- name: resource-web-hw

#outputs:
#- name: build/libs

run:
  path: resource-web-hw/gradlew
  args: ["bootRepackage"]
  #dir: resource-web-hw
  user: root