---
# Concourse task
platform: linux

image_resource:
  type: docker-image
  source:
    repository: gradle
    tag: 'jdk8'

inputs:
- name: resource-web-hw

run:
  path: gradle
  args: ["bootRepackage", "--info"]
  dir: resource-web-hw