---
# Concourse task
platform: linux

image_resource:
  type: docker-image
  source:
    repository: gradle
    tag: 'jdk8'

inputs:
- name: resource-web-hw

run:
  path: ls
  #args: ["resource-web-hw/gradlew", "bootRepackage"]
  #dir: resource-web-hw