---
# Concourse task
platform: linux

image_resource:
  type: docker-image
  source:
    repository: gradle
    tag: '4.2.1-jre8'

inputs:
- name: resource-web-hw

run:
  path: resource-web-hw/gradlew
  args: ["bootRepackage"]