---
# This is meant to be configured by the CI during build
datasource:
  sampleapp:
    maxPoolSize: 20
    defaultSchema:
    hibernate:
      hbm2ddl.method: create # update # or create for initial database deployment
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect